// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(GFootDbContext))]
    [Migration("20250501111301_updateFactoryEmissionAttr")]
    partial class updateFactoryEmissionAttr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Factory.EnvironmentalAgent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.ToTable("EnvironmentalAgents");
                });

            modelBuilder.Entity("Domain.Entities.Factory.FactoriesEnvironmentalAgents", b =>
                {
                    b.Property<string>("FactoryUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EnvironmentalAgentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FactoryUserId", "EnvironmentalAgentId");

                    b.HasIndex("EnvironmentalAgentId");

                    b.ToTable("FactoriesEnvironmentalAgents");
                });

            modelBuilder.Entity("Domain.Entities.Factory.FactoryEmission", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("AverageContainerWeight")
                        .HasColumnType("real");

                    b.Property<float?>("AverageEmployeeCommutingDistance")
                        .HasColumnType("real");

                    b.Property<float?>("AverageShippingDistance")
                        .HasColumnType("real");

                    b.Property<decimal?>("AverageTruckDistance")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("AverageTruckWeight")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("BusinessTravelFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessTravelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CarbonEmission")
                        .HasColumnType("decimal(12,4)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ElectricityConsumptionAmount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("ElectricityConsumptionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCommutingCar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCommutingCarpool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCommutingPublic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCommutingWalkOrCycle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnergyIntensiveProcesses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("FacilitySize")
                        .HasColumnType("real");

                    b.Property<string>("FactoryUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FuelConsumptionAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelConsumptionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustrialProcesses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustrialProcessesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfEmployees")
                        .HasColumnType("int");

                    b.Property<string>("OwnedTransportation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenewableElectricitySource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPartyShipping")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("TruckFuelAmount")
                        .HasColumnType("real");

                    b.Property<string>("TruckFuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruckType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WasteDisposalMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WasteGenerated")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("WasteType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("WaterConsumption")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FactoryUserId");

                    b.ToTable("FactoryEmissions");
                });

            modelBuilder.Entity("Domain.Entities.Factory.FactoryRecommendation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("FactoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("FactoryRecommendations");
                });

            modelBuilder.Entity("Domain.Entities.Factory.FactoryUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IndustryType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.ToTable("FactoryUsers");
                });

            modelBuilder.Entity("Domain.Entities.Factory.GuestServiceRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GuestServiceRequests");
                });

            modelBuilder.Entity("Domain.Entities.Factory.Report", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateGenerated")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnvironmentalAgentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FactoryUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("OnLatestCalculation")
                        .HasColumnType("bit");

                    b.Property<string>("ReportBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentalAgentId");

                    b.HasIndex("FactoryUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Domain.Entities.Factory.SensorData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DataValue")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("FactoryUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FactoryUserId");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailConfirmationOTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("OTPExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetOTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetOTPExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Individual.Activity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AirTravelFreq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CarbonEmission")
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("DailyInternetUsage")
                        .HasColumnType("int");

                    b.Property<int>("DailyTvTime")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnergyEfficiency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GroceryBill")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("HeatingSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthlyClothingPurchases")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowerFreq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialActivity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("VehicleDistanceKm")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WasteBagSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WasteBagWeeklyCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Domain.Entities.Individual.IndividualRecommendation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IndividualRecommendations");
                });

            modelBuilder.Entity("Domain.Entities.Individual.IndividualUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.ToTable("IndividualUsers");
                });

            modelBuilder.Entity("Domain.Entities.Individual.Notification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDate()");

                    b.Property<string>("NotificationBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Factory.EnvironmentalAgent", b =>
                {
                    b.HasOne("Domain.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne("EnvironmentalAgent")
                        .HasForeignKey("Domain.Entities.Factory.EnvironmentalAgent", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Domain.Entities.Factory.FactoriesEnvironmentalAgents", b =>
                {
                    b.HasOne("Domain.Entities.Factory.EnvironmentalAgent", "EnvironmentalAgent")
                        .WithMany("FactoryOrganizations")
                        .HasForeignKey("EnvironmentalAgentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Factory.FactoryUser", "Factory")
                        .WithMany("FactoryOrganizations")
                        .HasForeignKey("FactoryUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EnvironmentalAgent");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("Domain.Entities.Factory.FactoryEmission", b =>
                {
                    b.HasOne("Domain.Entities.Factory.FactoryUser", "Factory")
                        .WithMany("FactoryEmissions")
                        .HasForeignKey("FactoryUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("Domain.Entities.Factory.FactoryRecommendation", b =>
                {
                    b.HasOne("Domain.Entities.Factory.FactoryUser", "FactoryUser")
                        .WithMany("FactoryRecomendations")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FactoryUser");
                });

            modelBuilder.Entity("Domain.Entities.Factory.FactoryUser", b =>
                {
                    b.HasOne("Domain.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne("FactoryUser")
                        .HasForeignKey("Domain.Entities.Factory.FactoryUser", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Domain.Entities.Factory.Report", b =>
                {
                    b.HasOne("Domain.Entities.Factory.EnvironmentalAgent", "EnvironmentalAgent")
                        .WithMany("Reports")
                        .HasForeignKey("EnvironmentalAgentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Factory.FactoryUser", "Factory")
                        .WithMany("Reports")
                        .HasForeignKey("FactoryUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("EnvironmentalAgent");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("Domain.Entities.Factory.SensorData", b =>
                {
                    b.HasOne("Domain.Entities.Factory.FactoryUser", "Factory")
                        .WithMany("SensorData")
                        .HasForeignKey("FactoryUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("Domain.Entities.Individual.Activity", b =>
                {
                    b.HasOne("Domain.Entities.Individual.IndividualUser", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Individual.IndividualRecommendation", b =>
                {
                    b.HasOne("Domain.Entities.Individual.IndividualUser", "User")
                        .WithMany("IndividualRecommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Individual.IndividualUser", b =>
                {
                    b.HasOne("Domain.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne("IndividualUser")
                        .HasForeignKey("Domain.Entities.Individual.IndividualUser", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Domain.Entities.Individual.Notification", b =>
                {
                    b.HasOne("Domain.Entities.Individual.IndividualUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Factory.EnvironmentalAgent", b =>
                {
                    b.Navigation("FactoryOrganizations");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Domain.Entities.Factory.FactoryUser", b =>
                {
                    b.Navigation("FactoryEmissions");

                    b.Navigation("FactoryOrganizations");

                    b.Navigation("FactoryRecomendations");

                    b.Navigation("Reports");

                    b.Navigation("SensorData");
                });

            modelBuilder.Entity("Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("EnvironmentalAgent");

                    b.Navigation("FactoryUser");

                    b.Navigation("IndividualUser");
                });

            modelBuilder.Entity("Domain.Entities.Individual.IndividualUser", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("IndividualRecommendations");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
